### ISSUE TITLE
DB에 중복으로 요청하는것 해결

### ISSUE THREAD

**Issue by Trashnokdu** [LYNC-TEAM/LYNC-Backend#29]
메소드 : POST

엔드포인트 : /creator/SignIn

컨트롤러 : creator.controller.ts

함수 : SignIn

설명:
유저ID로 유저정보를 불러와서 userdata에 저장한 후에 Password 대조용으로 다시 DB에 query하는점을 수정해야합니다

**Comment by wondev07** [comment]
혹시 몇번줄인지 알수 있을까요??

**Comment by wondev07** [comment]
해당부분 수정해서 develop 브런치에 푸쉬하겠습니다 이슈 해결되었는지 확인 한번 해주시고
추가 이슈 없으면 머지 부탁드릴게여

**Comment by wondev07** [comment]
develop 브런치에 배포했습니다 확인한번 부탁드릴게요

**Comment by Trashnokdu** [comment]
#[7fccd1d](https://github.com/LYNC-TEAM/LYNC-Backend/commit/7fccd1de4bacd3c6506964a8a97cb4c9075ca9af)

이 커밋으로 해결되었습니다
